#!/usr/bin/env bash
name='debian-subsystem'
release='1'
version='master'
url='https://gitlab.com/sulincix/debian-subsystem'
description='Easy way to use debian chroot'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=('https://gitlab.com/sulincix/debian-subsystem/-/archive/master/debian-subsystem-master.zip')
depends=()
makedepends=()
md5sums=('SKIP')
group=()
uses=()
uses_extra=(pam)
arch=('x86_64')

cd $name-$version

build () {
    make lsl
    if use pam ; then
        make pam
    fi
}

package () {
    make install_data install_lsl DESTDIR=$DESTDIR
    if use pam ; then
        make install_pam DESTDIR=$DESTDIR
    fi
    mkdir -p $DESTDIR/etc/sysconf.d
    echo "#!/bin/sh" > $DESTDIR/etc/sysconf.d/debian-subsystem
    echo "chmod 4755 /bin/lsl" >> $DESTDIR/etc/sysconf.d/debian-subsystem
}

