#!/bin/bash
set -e
source /usr/lib/sulin/dsl/variable.sh

if [[ "$1" == "--no-install" ]] ; then
    if [[ ! -f "${DESTDIR}/etc/os-release" ]] ; then
        exit 0
    fi
fi

if [[ -f "$1" ]] ; then
    cat $1 | $(get_root) /usr/lib/sulin/dsl/dsl.sh
elif [[ "$1" == "-c" ]] ; then
    shift
    echo "$*" | $(get_root) /usr/lib/sulin/dsl/dsl.sh
elif [[ "$1" == "--update" ]] ; then
    source /usr/lib/sulin/dsl/functions.sh
    if ! check_update ; then
        echo "No update found. Already up to date."
        exit 0
    fi
elif [[ "$1" == "--help" ]] ; then
    echo "debian [options]"
    echo "  --help         : Write this message"
    echo "  -c             : Run command from subsystem"
    echo "  --no-install   : Do not install if not installed."
    echo "  --update       : Install update if exists."
else
    $(get_root) /usr/lib/sulin/dsl/dsl.sh
fi

