#!/bin/bash
hostctl-daemon &
cd /usr/lib/sulin/dsl
source /usr/lib/sulin/dsl/variable.sh
get_root(){
    if [[ $UID -ne 0 ]]; then
        if which pkexec &>/dev/null && [[ "$NOPKEXEC" == "" ]] ; then
            echo "exec pkexec"
        else
            echo "su -c"
        fi
    fi
}
$(get_root) /usr/lib/sulin/dsl/dsl.sh
