#!/bin/bash
cd /usr/lib/sulin/dsl
source variable.sh
source functions.sh
isroot
trim(){
    while read line ; do
        echo $line
    done
}
if [[ "$1" == "--help" ]] ; then
    echo "Usage: debian-umount [options]"
    echo "  --help:    write help message and exit"
    echo "  --kill:    kill running process under subsystem"
    echo "  --remove:  remove subsystem"
    exit 0
fi
ps ax | grep -v grep | grep "hostctl" | trim | cut -f "1" -d " " | xargs kill -9 &>/dev/null || true
rm -f "${DESTDIR}"/run/hostctl
if [[ "$1" == "--kill" ]] ; then
    set +e
    PID_LIST=$(ps aux | grep -v grep | grep dsl.sh | tr -s ' ' | cut -f 2 -d ' ')
    for p in ${PID_LIST[@]} ; do
        msg "Kill" "$p"
        kill -9 $p || true
    done
    pactl unload-module module-native-protocol-tcp &>/dev/null
    shift
    set -e
fi
umount_all

if [[ "$1" == "--remove" ]] ; then
    rm -rf "${DESTDIR}"
    rm -rf /usr/share/applications/debian/*.desktop
fi
