#!/bin/bash
cd /usr/lib/sulin/dsl
source variable.sh
source functions.sh
trim(){
    while read line ; do
        echo $line
    done
}
ps ax | grep -v grep | grep "/usr/bin/hostctl-daemon$" | trim | cut -f "1" -d " " | xargs kill -9 &>/dev/null || true
rm -f /tmp/hostctl
umount_all

if [[ "$1" == "--remove" ]] ; then
    rm -rf "${DESTDIR}"
fi
