#!/bin/bash
if ! ls /tmp/hostctl &>/dev/null ; then
    echo -e "Failed to connect hostctl."
    exit 1
fi
timeout 3 echo "$*" > /run/hostctl || {
    echo -e "Failed to connect hostctl."
    exit 1

}
