#!/bin/bash
if [[ ! -f /var/debian/etc/os-release ]] ; then
    exit 1
fi
trim(){
    while read line ; do
    echo $line
done
}
ps ax | grep -v grep | grep "/usr/bin/hostctl-daemon$" | grep -v "$$" &>/dev/null && exit 0
rm -f /var/debian/tmp/hostctl || true
mkfifo /var/debian/tmp/hostctl &>/dev/null || true
 echo "##### $(LANG=C date) ##### CREATING DAEMON #####" >> ~/.local/hostctl.log
while true ; do
    while read line < /var/debian/tmp/hostctl
    do
        echo "##### $(LANG=C date) ##### $line #####" >> ~/.local/hostctl.log
        $line &>> ~/.local/hostctl.log &
        sleep 0.3
    done
done
