#!/bin/bash
source /usr/lib/sulin/dsl/variable.sh
if [[ ! -f ${DESTDIR}/etc/os-release ]] ; then
    exit 1
fi
trim(){
    while read line ; do
    echo $line
done
}
ps ax | grep -v grep | grep "/usr/bin/hostctl-daemon$" | grep -v "$$" &>/dev/null && exit 0
rm -f ${DESTDIR}/tmp/hostctl || true
mkfifo ${DESTDIR}/tmp/hostctl &>/dev/null || true
 echo "##### $(LANG=C date) ##### CREATING DAEMON #####" >> ~/.local/hostctl.log
while true ; do
    while read line < ${DESTDIR}/tmp/hostctl
    do
        echo "##### $(LANG=C date) ##### $line #####" >> ~/.local/hostctl.log
        $line &>> ~/.local/hostctl.log &
        sleep 0.3
    done
done
