#!/bin/bash
if [[ ! -f /var/debian/etc/os-release ]] ; then
    exit 1
fi
if ps aux | grep -v grep | grep /var/debian/tmp/hostctl &>/dev/null ; then
    exit 0
fi
mkfifo /var/debian/tmp/hostctl || true
while true ; do
    cat /var/debian/tmp/hostctl | while read line
    do
        $line &
        sleep 0.3
    done
done
