#!/bin/bash
if [[ "$1" != "purge" ]] ; then
    exit 0
fi
set -ex
set -o pipefail
while grep /var/lib/subsystem/var/lib/lsl/system /proc/mounts ; do
    umount -lf /var/lib/subsystem/var/lib/lsl/system/
done
ls /var/lib/subsystem \
    | grep -v dev \
    | grep -v sys \
    | grep -v proc \
    | grep -v run \
    | grep -v tmp \
    | grep -v home \
    | grep -v root \
    | sed  "s|^|rm -rfv /var/lib/subsystem/|g" \
    | sh -ex
