#!/bin/bash
set -ex
set -o pipefail
if grep /var/lib/subsystem/var/lib/lsl/system /proc/mounts ; then
    umount -lf /var/lib/subsystem/var/lib/lsl/system/
fi
ls /var/lib/subsystem \
    | grep -v dev \
    | grep -v sys \
    | grep -v proc \
    | grep -v run \
    | grep -v tmp \
    | grep -v home \
    | grep -v root \
    | sed  "s|^|rm -rfv /var/lib/subsystem/|g" \
    | sh -ex
