#!/bin/bash
[[ -f "$1" ]] && exec debian-xdg-open $@
source /usr/lib/sulin/dsl/variable.sh
if [[ -f /usr/lib/sulin/dsl/d-term ]] ; then
    /usr/lib/sulin/dsl/d-term "$(get_root) /usr/lib/sulin/dsl/dsl.sh"
elif which xterm &>/dev/null ; then
    xterm -e "$(get_root) /usr/lib/sulin/dsl/dsl.sh"
fi
