#!/bin/bash
[[ -f "$1" ]] && exec debian-xdg-open $@
source /usr/lib/sulin/dsl/variable.sh
if [[ $(get x-terminal-emulator) != "" ]] ; then
    if [[ $(get x-terminal-emulator) == "d-term" ]] ; then
        /usr/lib/sulin/dsl/d-term "$(get_root) /usr/lib/sulin/dsl/dsl.sh"
    fi
    $(get_root) /usr/lib/sulin/dsl/dsl.sh <<< "$(get x-terminal-emulator)"
elif ls ${DESTDIR}/usr/bin/x-terminal-emulator &>/dev/null ; then
    $(get_root) /usr/lib/sulin/dsl/dsl.sh <<< x-terminal-emulator
elif [[ -f /usr/lib/sulin/dsl/d-term ]] ; then
    /usr/lib/sulin/dsl/d-term "$(get_root) /usr/lib/sulin/dsl/dsl.sh"
elif which xterm &>/dev/null ; then
    xterm -e "$(get_root) /usr/lib/sulin/dsl/dsl.sh"
fi
