#!/bin/bash
tool_init(){
    which apk &>/dev/null && return 0
    mkdir -p /tmp/apk
    cd /tmp/apk
    arch="$(uname -m)"
    apktools=$($wget -O - https://dl-cdn.alpinelinux.org/alpine/latest-stable/main/$arch/ | grep "apk-tools-static" | sed "s/^.*=\"//g;s/\".*//g")
    $wget -c "https://dl-cdn.alpinelinux.org/alpine/latest-stable/main/$arch/$apktools" -O apk-tools-static.apk || fail_exit "Failed to fetch apt-tools"
    tar -zxf apk-tools-static.apk
    cp -pf sbin/apk.static /bin/apk
    chmod +x /bin/apk

}
system_init(){
    ls ${DESTDIR}/etc/alpine-release &>/dev/null && return 0
    arch="$(uname -m)"
    apk --arch $arch -X "${REPO}/main/" -U --allow-untrusted --root ${DESTDIR} --initdb add alpine-base bash || fail_exit "Failed to install archlinux chroot"
    sync
    echo "${REPO}/main/" > ${DESTDIR}/etc/apk/repositories
    echo "${REPO}/community/" >> ${DESTDIR}/etc/apk/repositories

}
create_user(){
    chroot "${DESTDIR}" adduser "${USERNAME}" -D -H -h "/home/${USERNAME}" -s /bin/ash || fail_exit "Failed to create user"
    mkdir -p "${DESTDIR}/home/"${USERNAME}""
}
