#!/bin/bash
set -e
tool_init(){
    which fdstrap &>/dev/null && return 0
    cd /tmp
    $wget -c https://gitlab.com/tearch-linux/applications-and-tools/fdstrap/-/raw/main/fdstrap.sh -O fdstrap.sh || fail_exit "Failed to fetch arch-bootstrap"
    cp -fp fdstrap.sh /usr/bin/fdstrap
    chmod 755 /usr/bin/fdstrap
}
system_init(){
    ls ${DESTDIR}/etc/os-release &>/dev/null && return 0
    fdstrap "${DESTDIR}" || fail_exit "Failed to install fedora chroot"
}
create_user(){
    chroot "${DESTDIR}" useradd "${USERNAME}" -d "/home/${USERNAME}" -s /bin/bash || fail_exit "Failed to create user"
    mkdir -p "${DESTDIR}/home/${USERNAME}"
}
