#!/bin/bash
tool_init(){
    which sulinstrapt &>/dev/null && return 0
    cd /tmp
    $wget -c "https://gitlab.com/sulinos/devel/inary/-/raw/develop/scripts/sulinstrapt" -O sulinstrapt.sh || fail_exit "Failed to fetch arch-bootstrap"
    cp -fp sulinstrapt.sh /usr/bin/sulinstrapt
    chmod 755 /usr/bin/sulinstrapt
}
system_init(){
    ls ${DESTDIR}/data/user &>/dev/null && return 0
    sulinstrapt "${DESTDIR}" -r "${REPO}"
}
create_user(){
    chroot "${DESTDIR}" useradd d"${USERNAME}" -d "/data/user/${USERNAME}" -s /bin/bash || fail_exit "Failed to create user"
    mkdir -p "${DESTDIR}/data/user/${USERNAME}"
    ln -s data/user "${DESTDIR}/home"
}
