#!/bin/bash
tool_init(){
    which xbps-static &>/dev/null && return 0
    cd /tmp
    arch="$(uname -m)"
    $wget -c "https://alpha.de.repo.voidlinux.org/static/xbps-static-latest.$arch-musl.tar.xz" -O xbps-static-latest.x86_64-musl.tar.xz
    tar -xf xbps-static-latest.x86_64-musl.tar.xz
    cp -pf ./usr/bin/xbps-install.static /bin/xbps-install
}
system_init(){
    ls ${DESTDIR}/etc/os-release &>/dev/null && return 0
    yes | SSL_NO_VERIFY_PEER=1 XBPS_ARCH=$arch xbps-install -f -S -r ${DESTDIR} -R "$REPO" base-system -y
}

create_user(){
    chroot "${DESTDIR}" useradd "${USERNAME}" -d "/home/${USERNAME}" -s /bin/bash || fail_exit "Failed to create user"
    mkdir -p "${DESTDIR}/home/${USERNAME}"
}
